# Generated by Django 4.1.7 on 2023-04-27 13:35

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.CharField(default='bc035ca6e61202b087ea6e54568009a05cbe888d67b3a7026ee19e22c1dd3779', max_length=64)),
                ('test', models.CharField(default='a', max_length=5)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BlockStruct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockID', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('blockID',),
            },
        ),
        migrations.CreateModel(
            name='TxModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_add', models.CharField(default='0000000', max_length=64)),
                ('to_address', models.CharField(max_length=64)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
