# Generated by Django 4.1.7 on 2023-04-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockStruct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockID2', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('blockID2',),
            },
        ),
    ]
