# Generated by Django 4.1.7 on 2023-05-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tx',
            name='message',
            field=models.TextField(default='None', max_length=512),
        ),
    ]
