# Generated by Django 4.1.7 on 2023-04-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockstruct',
            name='blockID',
            field=models.CharField(default='a', max_length=20),
        ),
    ]
