# Generated by Django 4.1.7 on 2023-04-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='address',
            field=models.CharField(default='d29a06470098f9fb5fb1320a2f2eaa021abdc030de6dd6fab5a63e04aa803dba', max_length=64),
        ),
    ]
