# Generated by Django 4.1.7 on 2023-04-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tx',
            name='block',
        ),
        migrations.AddField(
            model_name='block',
            name='txs',
            field=models.ManyToManyField(to='chain.tx'),
        ),
    ]
