# Generated by Django 4.1.7 on 2023-04-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0002_blockstruct_blockid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockstruct',
            options={'ordering': ('blockID',)},
        ),
        migrations.RemoveField(
            model_name='blockstruct',
            name='blockID2',
        ),
        migrations.AlterField(
            model_name='blockstruct',
            name='blockID',
            field=models.CharField(max_length=20),
        ),
    ]
