# Generated by Django 4.1.7 on 2023-04-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0002_alter_accountmodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='address',
            field=models.CharField(default='30ce558f5c41187948639eacc31f67fc3803117f36248b44152f80b78a0c3d89', max_length=64),
        ),
    ]
