# Generated by Django 4.1.7 on 2023-05-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0002_alter_block_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tx',
            name='fee',
            field=models.FloatField(default=0.01, editable=False),
        ),
    ]
