# Generated by Django 4.1.7 on 2023-04-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0003_alter_accountmodel_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountmodel',
            options={'verbose_name': 'Accounts Model'},
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='address',
            field=models.CharField(default='0fafda3bc05bf1082653f0776234a57f81a36894fefa9c0f216c45ca458ac28b', max_length=64),
        ),
    ]
