# Generated by Django 4.1.7 on 2023-05-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0005_alter_block_total_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pending_amount',
            field=models.FloatField(default='0', editable=False, max_length=5),
        ),
    ]
