# Generated by Django 4.1.7 on 2023-05-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0006_account_pending_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tx',
            name='fee',
            field=models.FloatField(default=0.005),
        ),
    ]
