# Generated by Django 4.1.7 on 2023-05-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0007_alter_tx_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tx',
            name='fee',
            field=models.FloatField(default=0.01),
        ),
    ]
