# Generated by Django 4.1.7 on 2023-05-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0008_alter_tx_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tx',
            name='amount',
            field=models.IntegerField(default='0'),
        ),
    ]
