# Generated by Django 4.1.7 on 2023-05-09 11:51

import chain.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0009_alter_tx_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tx',
            name='amount',
            field=models.IntegerField(default='0', validators=[chain.models.validate_amount]),
        ),
    ]
