# Generated by Django 4.1.7 on 2023-05-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0010_alter_tx_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default='0', editable=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='pending_amount',
            field=models.IntegerField(default='0', editable=False),
        ),
    ]
