# Generated by Django 4.1.7 on 2023-05-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0011_alter_account_balance_alter_account_pending_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tx',
            name='public_key',
            field=models.BinaryField(default=b'empty_pk'),
        ),
        migrations.AddField(
            model_name='tx',
            name='signature',
            field=models.BinaryField(default=b'empty_signature'),
        ),
    ]
