# Generated by Django 4.1.7 on 2023-05-13 13:48

import chain.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.CharField(default='00000000000000000000000000000000', editable=False, max_length=64)),
                ('balance', models.IntegerField(default='0', editable=False)),
                ('pending_amount', models.IntegerField(default='0', editable=False)),
            ],
            options={
                'verbose_name': 'Accounts Model',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(default='0000000', editable=False, max_length=64)),
                ('to_address', models.CharField(default='0000000', max_length=64)),
                ('amount', models.IntegerField(default='0', validators=[chain.models.validate_amount])),
                ('executed', models.BooleanField(default=False)),
                ('tx_type', models.CharField(default='ordinary', max_length=64)),
                ('message', models.TextField(default='None', max_length=512)),
                ('fee', models.FloatField(default=0.01)),
                ('signature', models.BinaryField(default=b'empty_signature')),
                ('public_key', models.BinaryField(default=b'empty_pk')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fee', models.FloatField(default=0, editable=False)),
                ('miner_address', models.CharField(default='0x0', editable=False, max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nonce', models.IntegerField(default=0, editable=False)),
                ('previous_hash', models.CharField(default='GENESIS BLOCK', editable=False, max_length=64)),
                ('hash', models.CharField(default='0x0', editable=False, max_length=64)),
                ('reward', models.IntegerField(default=100, editable=False)),
                ('txs', models.ManyToManyField(blank=True, default=None, to='chain.tx')),
            ],
        ),
    ]
